name: sar_drift_converter
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - geopandas
  - matplotlib
  - netCDF4  
  - numpy
  - pandas
  - pip
  - pip:
      - nc-time-axis  
  - pyproj
  - python=3.10
  - rasterio  
  - scipy
  - scikit-learn
  - shapely
  - tqdm
  - xarray